<template>
  <div class="hero">
    <div class="hero-content">
      <h1>2025年の日本旅行</h1>
      <p>6 — 22 октября 2025 • 16 дней</p>
      <p>Времени до поездки: <span id="countdown" class="countdown-timer">{{ timeLeft }}</span></p>
    </div>
  </div>

  <!-- Stats Section -->
  <div class="section">
    <div class="container">
      <div class="stats">
        <div class="stat-card">
          <div class="stat-number">16</div>
          <div class="stat-label">Дней в Японии</div>
        </div>
        <div class="stat-card">
          <div class="stat-number">5</div>
          <div class="stat-label">Городов</div>
        </div>
        <div class="stat-card">
          <div class="stat-number">20+</div>
          <div class="stat-label">Достопримечательностей</div>
        </div>
        <div class="stat-card">
          <div class="stat-number">3</div>
          <div class="stat-label">Острова</div>
        </div>
      </div>
    </div>
  </div>

  <!-- Timeline Section -->
  <div class="section">
    <div class="container">
      <h2 class="section-title">Маршрут поездки</h2>
      <div class="timeline" id="timeline">
        <!-- Day cards will be generated by JavaScript -->
      </div>
    </div>
  </div>

  <!-- Places Section -->
  <div class="section" style="background: linear-gradient(135deg, #f5f7fa 0%, #c3cfe2 100%);">
    <div class="container">
      <h2 class="section-title">Места для посещения</h2>
      <div class="places-grid" id="places-grid">
        <!-- Place cards will be generated by JavaScript -->
      </div>
      <h2 class="section-title">Нужно сделать</h2>
      <h2 class="section-title">Лайфхаки</h2>
    </div>
  </div>

  <!-- Modal -->
  <div class="modal" id="modal">
    <div class="modal-content">
      <button class="close-modal">&times;</button>
      <div id="modal-body"></div>
    </div>
  </div>

  <!-- Floating Navigation -->
  <ScrollToTop />
</template>

<script setup lang="ts">
import { ref, onMounted, onUnmounted } from 'vue'
import { itinerary } from "@/pages/Home/data/itinerary.ts"
import { places } from "@/pages/Home/data/places.ts"
import ScrollToTop from '@/components/ScrollToTop.vue'

const timeLeft = ref('')
let countdownInterval: number | null = null

const tripDate = new Date('2025-10-05T20:05:00Z')

function updateCountdown() {
  const now = new Date()
  const difference = tripDate.getTime() - now.getTime()
  
  if (difference > 0) {
    const days = Math.floor(difference / (1000 * 60 * 60 * 24))
    const hours = Math.floor((difference % (1000 * 60 * 60 * 24)) / (1000 * 60 * 60))
    const minutes = Math.floor((difference % (1000 * 60 * 60)) / (1000 * 60))
    const seconds = Math.floor((difference % (1000 * 60)) / 1000)
    
    const formattedDays = String(days).padStart(2, '0')
    const formattedHours = String(hours).padStart(2, '0')
    const formattedMinutes = String(minutes).padStart(2, '0')
    const formattedSeconds = String(seconds).padStart(2, '0')
    
    timeLeft.value = `${formattedDays}:${formattedHours}:${formattedMinutes}:${formattedSeconds}`
  } else {
    timeLeft.value = '00:00:00:00'
  }
}

onMounted(() => {
  updateCountdown()
  countdownInterval = setInterval(updateCountdown, 1000)
})

onUnmounted(() => {
  if (countdownInterval) {
    clearInterval(countdownInterval)
  }
})

function createTimelineCards() {
  const timeline = document.getElementById('timeline');
  itinerary.forEach((day, index) => {
    const dayCard = document.createElement('div');
    dayCard.className = 'day-card';
    dayCard.innerHTML = `
                    <div class="day-number">${index + 1}</div>
                    <div class="card-content">
                        <div class="day-header">
                            <div class="day-emoji">${day.emoji}</div>
                            <div class="day-info">
                                <div class="day-date">${day.date}</div>
                                <div class="day-title">${day.title}</div>
                            </div>
                        </div>
                        <div class="day-description">${day.description}</div>
                    </div>
                `;
    timeline.appendChild(dayCard);
  });
}

function createPlaceCards() {
  const placesGrid = document.getElementById('places-grid');
  places.forEach(place => {
    const placeCard = document.createElement('div');
    placeCard.className = 'place-card';
    placeCard.onclick = () => showPlaceModal(place);
    placeCard.innerHTML = `
                    <div class="place-image">${place.emoji}</div>
                    <div class="place-content">
                        <div class="place-title">${place.title}</div>
                        <div class="place-description">${place.description}</div>
                    </div>
                `;
    placesGrid.appendChild(placeCard);
  });
}

function showPlaceModal(place) {
  const modal = document.getElementById('modal');
  const modalBody = document.getElementById('modal-body');
  modalBody.innerHTML = `
                <div style="text-align: center; margin-bottom: 1rem;">
                    <div style="font-size: 4rem; margin-bottom: 1rem;">${place.emoji}</div>
                    <h2 style="color: #333; margin-bottom: 1rem;">${place.title}</h2>
                    <p style="color: #666; line-height: 1.6;">${place.description}</p>
                </div>
            `;
  modal.style.display = 'flex';
}

function closeModal() {
  document.getElementById('modal').style.display = 'none';
}


function observeElements() {
  const observer = new IntersectionObserver((entries) => {
    entries.forEach(entry => {
      if (entry.isIntersecting) {
        entry.target.classList.add('visible');
      }
    });
  }, { threshold: 0.1 });

  document.querySelectorAll('.day-card').forEach(card => {
    observer.observe(card);
  });
}

// Initialize
document.addEventListener('DOMContentLoaded', function() {
  createTimelineCards();
  createPlaceCards();
  observeElements();

  // Close modal events
  document.querySelector('.close-modal').onclick = closeModal;
  document.getElementById('modal').onclick = function(e) {
    if (e.target === this) closeModal();
  };
});
</script>

<style scoped>
.countdown-timer {
  font-family: 'Courier New', monospace;
  font-size: 1.2em;
  font-weight: bold;
  color: #e74c3c;
  background: rgba(231, 76, 60, 0.1);
  padding: 4px 8px;
  border-radius: 4px;
  letter-spacing: 1px;
}
</style>